---
title: "Week 30"
author: "Calum Watt"
date: "22/07/2021"
output: html_document
---

# US drougtht dataset

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
dir()
```

* Let's get our libraries loaded
```{r Required libraries, warning=FALSE, message=FALSE}
require(tidyverse)
require(tidytuesdayR)
require(devtools)
require(urbnmapr) # this packages provides coordinate for state and shires (US)

# for animation
require(gganimate)
require(transformr)
require(gifski)
require(Rcpp)
require(maps)
require(janitor)
require(lubridate)
require(tibbletime)
```


```{r Download the data and clean}
drought <- read.csv("all USA data.csv") %>%
  pivot_longer(cols = None:D4, names_to = "Drought_level", values_to = "Percent Area") %>%
  janitor::clean_names() %>%
  mutate(drought_level = factor(drought_level, levels = c("D4", "D3", "D2","D1","D0", "None"))) %>%
  filter(!is.na(drought_level)) 

head(drought)

temp <- drought %>%
  group_by(fips, valid_start) %>%
  arrange(fips, valid_start, desc(percent_area), drought_level) %>%
  slice(1) #slice selects the first row in each group, a group being fips and valid_date. therefore removes unnecessary rows

```

```{r add the fips}
data("county.fips") # the fips data which we can associate to county

# clean up the polyname variable
county.fips <- county.fips %>%
  mutate(region = word(polyname,1, sep = ","),
         subregion = word(polyname, 2, sep = ","))%>%
  mutate(subregion = word(subregion, 1, sep = ":"))#only keep words prior to the colon

head(county.fips)

# get the USA map coordinate points and join with fips
map_us <- map_data("county")

map_us <- map_us %>%
  left_join(county.fips) %>%
  select(!polyname) 

```

```{r}
# join drought data from the temp file to the USA map
map_us <- map_us %>%
  left_join(temp)

# recode the droughth levels
map_us <- map_us %>%
  mutate(drought_level = fct_recode(drought_level,"Abnormally dry" = "D0",
                                    "Moderate" = "D1",
                                    "Severe" = "D2",
                                    "Extreme" = "D3",
                                    "Catastrophic" = "D4"))
str(map_us)
```

```{r plotting}
colours <- scales::seq_gradient_pal("white", "red")(seq(0,1,length.out = 6))

#NAs within the dataframe, remove. 
map_us <- map_us[!is.na(map_us),]

anim <- map_us %>%
  ungroup() %>%
  mutate(valid_start = as.Date(valid_start)) %>%
  filter(valid_start > "2019-10-01") %>%

#plotting
  ggplot() +
  geom_polygon(aes(long, lat, group = group,fill = fct_rev(drought_level))) +
  borders("county", colour = "grey") +
  borders("state", colour = "black") + 
  
  coord_map() +
  theme_minimal() +
  scale_fill_manual(values = colours, name = "Drought Category") +

#set the transition from week to week
  transition_manual(frames = valid_start) +

#plot labels
  labs(title = "Drought level across each county",
       subtitle = "Week starting: {current_frame}",
       caption = "#TidyTuesday | @calumwatt12 | 25-07-2021")

animate(anim, height = 5, width = 7, units = "in", res = 1000, renderer = gifski_renderer("USA droughts by shire.gif"))
```
