---
title: "Tidy Tuesday week 29"
author: "Dr Watt"
date: "16/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r include=FALSE}
require(tidyverse)
require(tidytuesdayR)
require(splitstackshape)
```

```{r Have a look at the data}
scooby <- 
  tidytuesdayR::tt_load(2021,week = 29)
scooby <- 
  scooby$scoobydoo
glimpse(scooby)

#look like there are cells with multiple monster names, genders etc. that will need to be split
scooby %>%
  count(scooby$monster_amount, sort = TRUE) 

#perhaps remove any NULL rows and just deal with the arrested vs non-arrested
scooby %>%
  count(scooby$arrested, sort = TRUE)
```


```{r splitting and cleaning}
#there are monster amounts with 0, remove
scooby <- 
  scooby %>%
  filter(monster_amount != 0)

#subset out those columns where being arrested is ambigious
scooby <-
  scooby %>%
  filter(arrested != "NULL")

#split out the strings associated with monsters into long format
scooby1 <- 
  cSplit(scooby, c("monster_gender", "monster_name","monster_species","monster_type" ,"monster_subtype"), sep = ",", "long") %>% 
  na.exclude

#not interested in who caught who or who capture who
scooby1 <- scooby1[,c(1:17, 40:75)]
```

```{r calculate the proportion of males to females in each monster type, include=FALSE}
#get the proportion of males to females for each monster_type
proportion_gender <-
  scooby1 %>%
  count(monster_type, monster_gender) %>%
  group_by(monster_type) %>%
  mutate(prop = prop.table(n)) %>%
  arrange(prop) %>%
  mutate_at(4,round,2)

#there is a gender classified as "None" which equates to a plant, perhaps lets rename this level as Non-binary 
levels(proportion_gender$monster_gender)[3] <- "non-binary"
```

```{r echo=TRUE}
#remove the non-binary value because there is no need for its own plot
proportion_gender <-
  proportion_gender[proportion_gender$monster_gender != "non-binary",]

#annotate only the female facet
ann_text <- proportion_gender %>%
  filter(monster_gender == "Female")

final <- ggplot(proportion_gender, aes(x = as.factor(monster_type), y = (prop), fill = monster_type)) +
  geom_bar(stat = "identity") +
  coord_polar(start = 0) +
  theme_minimal() + 
  facet_wrap(~monster_gender) +
  labs(title = "Proportion of monsters by gender",
       caption = "#TidyTuesday Week 29 | 15-07-2021 | Dr Calum Watt | @calumwatt12", subtitle = "A distinct underrepresentation of female \nmonsters across the
       years") +
  theme(legend.position = "bottom",
        legend.box = "horizontal",
        legend.title = element_blank(),
        panel.background = element_rect(fill = "white"),
        text = element_text(size =15),
        panel.grid.major.x = element_blank(),
        strip.background = element_blank(),
        axis.text = element_blank(),
        strip.text = element_text(size = 25, face = "bold"),
        axis.title = element_blank(),
        plot.title = element_text(hjust = 0.5, face = "bold", size = 50),
        plot.subtitle = element_text(hjust = 0.5, face = "italic", size = 25))+
  scale_y_continuous(trans = "sqrt") +
  geom_text(data = ann_text,y = 0.52, x= 3.5, label = "0.25", fontface = "bold", inherit.aes = FALSE) +
  geom_text(data = ann_text,y = 0.7, x= 3.5, label = "0.50", fontface = "bold", inherit.aes = FALSE) +
  geom_text(data = ann_text,y = 0.88, x= 3.5, label = "0.75", fontface = "bold", inherit.aes = FALSE) +
  geom_text(data = ann_text,y = 1.02, x= 3.5, label = "1", fontface = "bold", inherit.aes = FALSE) +
  geom_text(aes(label = prop), nudge_y = 0.05)

ggsave("monster genders.png", final, width = 17, height = 10, units = "in")

final
dev.off()
```
